using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Orqentis.Engine.Models;
using Orqentis.Engine.Odcs;

namespace Orqentis.AI;

/// <summary>Generates ODCS suggestions with timeout/retry/fallback behavior.</summary>
public sealed class ContractSuggestionAgent : IContractSuggestionAgent
{
    private const string _promptFile = "ContractSuggestion.txt";

    private readonly AiOptions _options;
    private readonly ILlmRouter _llmRouter;
    private readonly IPromptLoader _promptLoader;
    private readonly IOdcsContractValidator _validator;
    private readonly ILogger<ContractSuggestionAgent> _logger;

    public ContractSuggestionAgent(
        ILlmRouter llmRouter,
        IPromptLoader promptLoader,
        IOdcsContractValidator validator,
        IOptions<AiOptions> options,
        ILogger<ContractSuggestionAgent> logger)
    {
        _llmRouter = llmRouter;
        _promptLoader = promptLoader;
        _validator = validator;
        _options = options.Value;
        _logger = logger;
    }

    public async Task<ContractSuggestion> SuggestAsync(TableProfile profile, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(profile);
        var started = DateTimeOffset.UtcNow;
        var prompt = _promptLoader.Load(_promptFile);
        var userInput = BuildSuggestionInput(profile);

        _logger.LogDebug("AI-ContractSuggestion-Prompt Prompt={Prompt}", prompt);
        var llmResult = await _llmRouter.CompleteAsync("ContractSuggestion", prompt, userInput, ct).ConfigureAwait(false);

        var candidateYaml = StripCodeFences(llmResult?.Content);
        candidateYaml = SanitizeOdcsYaml(candidateYaml);
        if (!string.IsNullOrWhiteSpace(candidateYaml))
        {
            var validationErrors = _validator.Validate(candidateYaml);
            if (validationErrors.Count == 0)
            {
                return new ContractSuggestion
                {
                    OdcsYaml = candidateYaml,
                    Rationale = ["Generated by LLM from table profile metadata."],
                    ModelUsed = llmResult!.ModelUsed,
                    Latency = DateTimeOffset.UtcNow - started,
                };
            }

            _logger.LogWarning(
                "AI-ContractSuggestion-LlmYamlInvalid Model={Model} ErrorCount={ErrorCount} Errors={Errors} YamlPrefix={YamlPrefix}",
                llmResult?.ModelUsed,
                validationErrors.Count,
                string.Join(" | ", validationErrors.Take(8)),
                candidateYaml.Length > 600 ? candidateYaml[..600] : candidateYaml);
        }

        _logger.LogWarning("AI-ContractSuggestion-FallbackUsed FallbackEnabled={FallbackEnabled}", _options.FallbackEnabled);
        var fallbackYaml = BuildFallbackYaml(profile);
        return new ContractSuggestion
        {
            OdcsYaml = fallbackYaml,
            Rationale = ["Fallback template generated because model output was unavailable or invalid."],
            ModelUsed = "fallback-template",
            Latency = DateTimeOffset.UtcNow - started,
        };
    }

    private static string BuildSuggestionInput(TableProfile profile)
    {
        var payload = new
        {
            tableName = profile.TableName,
            abfssUri = profile.AbfssUri,
            columns = profile.Columns,
            sampleRows = profile.SampleRows,
        };

        return JsonSerializer.Serialize(payload);
    }

    private static string BuildFallbackYaml(TableProfile profile)
    {
        var columns = profile.Columns.Count == 0
            ? [new TableProfileColumn("id", "string", false, null, 0)]
            : profile.Columns;
        var escapedName = EscapeYaml(profile.TableName);
        var escapedPath = EscapeYaml(profile.AbfssUri);

        var builder = new StringBuilder();
        builder.AppendLine("apiVersion: v3.1.0");
        builder.AppendLine("kind: DataContract");
        builder.AppendLine("id: urn:orqentis:orqentis:CONTRACT_ID");
        builder.AppendLine($"name: {escapedName}");
        builder.AppendLine("version: 0.1.0");
        builder.AppendLine("status: draft");
        builder.AppendLine("description:");
        builder.AppendLine($"  purpose: AI-generated draft for {escapedName}");
        builder.AppendLine("  usage: Contract bootstrap");
        builder.AppendLine("servers:");
        builder.AppendLine("  - server: fabric");
        builder.AppendLine("    type: azure");
        builder.AppendLine($"    location: {escapedPath}");
        builder.AppendLine("    format: delta");
        builder.AppendLine("schema:");
        builder.AppendLine($"  - name: {escapedName}");
        builder.AppendLine("    physicalType: table");
        builder.AppendLine($"    description: Schema for {escapedName}");
        builder.AppendLine("    properties:");

        foreach (var column in columns)
        {
            var logicalType = MapLogicalType(column.Type);
            var required = !column.Nullable && (column.NullCount ?? 0) == 0;
            var unique = column.DistinctCount.HasValue && column.DistinctCount > 0 && column.NullCount == 0;
            var pii = IsPii(column.Name);

            builder.AppendLine($"      - name: {EscapeYaml(column.Name)}");
            builder.AppendLine($"        logicalType: {logicalType}");
            builder.AppendLine($"        physicalType: {logicalType.ToUpperInvariant()}");
            builder.AppendLine($"        required: {required.ToString().ToLowerInvariant()}");
            builder.AppendLine($"        unique: {unique.ToString().ToLowerInvariant()}");
            builder.AppendLine($"        description: Column {EscapeYaml(column.Name)}");
            builder.AppendLine("        customProperties:");
            builder.AppendLine("          - property: pii");
            builder.AppendLine($"            value: {pii.ToString().ToLowerInvariant()}");
        }

        builder.AppendLine("customProperties:");
        builder.AppendLine("  - property: orqentisInfo");
        builder.AppendLine("    value:");
        builder.AppendLine($"      title: {escapedName}");
        builder.AppendLine("      description: AI-generated ODCS draft");
        builder.AppendLine("      owner: TBD");
        builder.AppendLine("  - property: orqentisFreshness");
        builder.AppendLine("    value:");
        builder.AppendLine("      maxAgeHours: 24");
        builder.AppendLine("      severity: warning");
        return builder.ToString();
    }

    private static readonly string[] _disallowedTopLevelKeys = ["quality", "freshness", "sla", "slas", "schedule"];
    private static readonly HashSet<string> _validQualityTypes = new(StringComparer.OrdinalIgnoreCase) { "library", "sql", "custom", "text" };

    /// <summary>Repairs common ODCS v3.1.0 validation issues in LLM-generated YAML so the
    /// caller doesn't lose otherwise good output to small schema drift. Specifically:
    /// (a) strips disallowed top-level keys (quality, freshness, sla, schedule); these belong
    ///     nested under schema/customProperties but LLMs often hoist them; and
    /// (b) coerces any `type:` field inside a `quality:` block to `library` when the LLM emits
    ///     a non-enum value like `type: nullRate` (it should be `type: library, rule: nullRate`).
    /// Line-based to avoid serialization round-trips that would normalize formatting.</summary>
    internal static string? SanitizeOdcsYaml(string? content)
    {
        if (string.IsNullOrWhiteSpace(content))
        {
            return content;
        }
        var lines = content.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var output = new StringBuilder(content.Length);
        var skipping = false;
        var qualityIndent = -1;
        foreach (var line in lines)
        {
            if (line.Length == 0 || line.TrimStart().StartsWith('#'))
            {
                if (!skipping)
                {
                    output.AppendLine(line);
                }
                continue;
            }
            if (!char.IsWhiteSpace(line[0]) && !line.StartsWith('-'))
            {
                var colonIdx = line.IndexOf(':');
                if (colonIdx > 0)
                {
                    var key = line[..colonIdx].Trim();
                    if (Array.IndexOf(_disallowedTopLevelKeys, key) >= 0)
                    {
                        skipping = true;
                        continue;
                    }
                }
                skipping = false;
                qualityIndent = -1;
                output.AppendLine(line);
                continue;
            }
            if (skipping)
            {
                continue;
            }

            var indent = CountLeadingSpaces(line);
            var trimmed = line.TrimStart();

            if (trimmed.StartsWith("quality:", StringComparison.OrdinalIgnoreCase))
            {
                qualityIndent = indent;
                output.AppendLine(line);
                continue;
            }
            if (qualityIndent >= 0 && indent <= qualityIndent && !trimmed.StartsWith('-'))
            {
                qualityIndent = -1;
            }
            if (qualityIndent >= 0)
            {
                // Within a quality: block, normalize any `type: <value>` whose value isn't an enum
                // member. Accept lines like `- type: nullRate` and `type: nullRate`.
                var keyStart = trimmed.StartsWith("- ", StringComparison.Ordinal) ? trimmed[2..] : trimmed;
                if (keyStart.StartsWith("type:", StringComparison.OrdinalIgnoreCase))
                {
                    var value = keyStart[5..].Trim().Trim('"').Trim('\'');
                    if (!string.IsNullOrEmpty(value) && !_validQualityTypes.Contains(value))
                    {
                        var dashPrefix = trimmed.StartsWith("- ", StringComparison.Ordinal) ? "- " : string.Empty;
                        var pad = new string(' ', indent);
                        var ruleIndent = new string(' ', indent + dashPrefix.Length);
                        output.AppendLine($"{pad}{dashPrefix}type: library");
                        output.AppendLine($"{ruleIndent}rule: {value}");
                        continue;
                    }
                }
            }

            output.AppendLine(line);
        }
        return output.ToString();
    }

    private static int CountLeadingSpaces(string s)
    {
        var n = 0;
        while (n < s.Length && s[n] == ' ')
        {
            n++;
        }
        return n;
    }

    private static string? StripCodeFences(string? content)
    {
        if (string.IsNullOrWhiteSpace(content))
        {
            return content;
        }
        var trimmed = content.Trim();
        if (!trimmed.StartsWith("```", StringComparison.Ordinal))
        {
            return trimmed;
        }
        var firstNewline = trimmed.IndexOf('\n');
        if (firstNewline < 0)
        {
            return trimmed;
        }
        var inner = trimmed[(firstNewline + 1)..];
        if (inner.EndsWith("```", StringComparison.Ordinal))
        {
            inner = inner[..^3];
        }
        return inner.Trim();
    }

    private static string EscapeYaml(string value)
    {
        if (value is null)
        {
            return "\"\"";
        }
        // Always emit as a double-quoted YAML scalar to safely carry colons, URIs,
        // and other YAML-reserved characters. Escape backslashes and quotes.
        var escaped = value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }

    private static string MapLogicalType(string sourceType)
    {
        var normalizedType = sourceType.Trim().ToLowerInvariant();
        return normalizedType switch
        {
            "int" or "integer" or "bigint" or "long" or "smallint" or "tinyint" or "short" or "byte" => "integer",
            "double" or "float" or "real" or "decimal" or "numeric" or "money" => "number",
            "bool" or "boolean" or "bit" => "boolean",
            "date" => "date",
            "time" => "time",
            "timestamp" or "datetime" or "datetime2" or "datetimeoffset" => "timestamp",
            "array" or "list" => "array",
            "struct" or "object" or "map" or "row" => "object",
            _ => "string",
        };
    }

    private static bool IsPii(string columnName)
    {
        var name = columnName.ToLowerInvariant();
        return name.Contains("email", StringComparison.Ordinal) ||
            name.Contains("phone", StringComparison.Ordinal) ||
            name.Contains("ssn", StringComparison.Ordinal) ||
            name.Contains("mrn", StringComparison.Ordinal) ||
            name.Contains("dob", StringComparison.Ordinal);
    }
}

/// <summary>Computes breach score with model fallback to null.</summary>
public sealed class BreachImpactScorer : IBreachImpactScorer
{
    private const string _promptFile = "BreachImpactScoring.txt";

    private readonly ILlmRouter _llmRouter;
    private readonly IPromptLoader _promptLoader;
    private readonly ILogger<BreachImpactScorer> _logger;

    public BreachImpactScorer(ILlmRouter llmRouter, IPromptLoader promptLoader, ILogger<BreachImpactScorer> logger)
    {
        _llmRouter = llmRouter;
        _promptLoader = promptLoader;
        _logger = logger;
    }

    public async Task<BreachScore?> ScoreAsync(
        EnforcementResult result,
        ContractDefinition contract,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(result);
        ArgumentNullException.ThrowIfNull(contract);

        var prompt = _promptLoader.Load(_promptFile);
        var input = JsonSerializer.Serialize(new { contract, result });
        _logger.LogDebug("AI-BreachImpact-Prompt Prompt={Prompt}", prompt);

        var llmResult = await _llmRouter.CompleteAsync("BreachImpact", prompt, input, ct).ConfigureAwait(false);
        if (llmResult is null || string.IsNullOrWhiteSpace(llmResult.Content))
        {
            return null;
        }

        try
        {
            using var document = JsonDocument.Parse(llmResult.Content);
            var score = document.RootElement.GetProperty("score").GetDecimal();
            var reasons = document.RootElement
                .GetProperty("reasons")
                .EnumerateArray()
                .Select(item => item.GetString())
                .Where(reason => !string.IsNullOrWhiteSpace(reason))
                .Cast<string>()
                .ToArray();
            var breakdown = new Dictionary<string, decimal>(StringComparer.OrdinalIgnoreCase)
            {
                ["ruleSeverityProfile"] = 35m,
                ["consumerCount"] = 25m,
                ["downstreamAiDependency"] = 20m,
                ["columnCriticality"] = 15m,
                ["freshnessMargin"] = 5m,
            };
            return new BreachScore(Math.Clamp(score, 0, 100), reasons, llmResult.ModelUsed, breakdown);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "AI-BreachImpact-ParseFailed");
            return null;
        }
    }
}

/// <summary>Improves an existing ODCS contract with better governance rules and PII annotations.</summary>
public sealed class ContractImprovementAgent : IContractImprovementAgent
{
    private const string _promptFile = "ContractImprove.txt";

    private readonly ILlmRouter _llmRouter;
    private readonly IPromptLoader _promptLoader;
    private readonly IOdcsContractValidator _validator;
    private readonly ILogger<ContractImprovementAgent> _logger;

    public ContractImprovementAgent(
        ILlmRouter llmRouter,
        IPromptLoader promptLoader,
        IOdcsContractValidator validator,
        ILogger<ContractImprovementAgent> logger)
    {
        _llmRouter = llmRouter;
        _promptLoader = promptLoader;
        _validator = validator;
        _logger = logger;
    }

    public async Task<ContractSuggestion> ImproveAsync(string odcsYaml, CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(odcsYaml);
        var started = DateTimeOffset.UtcNow;
        var prompt = _promptLoader.Load(_promptFile);

        _logger.LogInformation("AI-ContractImprove-Start YamlLength={Length}", odcsYaml.Length);
        var llmResult = await _llmRouter.CompleteAsync("ContractImprove", prompt, odcsYaml, ct).ConfigureAwait(false);

        var candidateYaml = llmResult?.Content?.Trim();
        if (!string.IsNullOrWhiteSpace(candidateYaml))
        {
            var errors = _validator.Validate(candidateYaml);
            if (errors.Count == 0)
            {
                _logger.LogInformation("AI-ContractImprove-Success Model={Model}", llmResult!.ModelUsed);
                return new ContractSuggestion
                {
                    OdcsYaml = candidateYaml,
                    Rationale = ["Contract improved with richer quality rules, PII annotations, and better descriptions."],
                    ModelUsed = llmResult.ModelUsed,
                    Latency = DateTimeOffset.UtcNow - started,
                };
            }

            _logger.LogWarning("AI-ContractImprove-ValidationFailed ErrorCount={Count}", errors.Count);
        }
        else
        {
            _logger.LogWarning("AI-ContractImprove-EmptyResponse");
        }

        // Fallback: return original YAML unchanged so the caller is never left with nothing.
        return new ContractSuggestion
        {
            OdcsYaml = odcsYaml,
            Rationale = ["AI improvement was unavailable; original contract returned unchanged."],
            ModelUsed = "fallback-passthrough",
            Latency = DateTimeOffset.UtcNow - started,
        };
    }
}

/// <summary>Generates remediation suggestions with safe empty fallback.</summary>
public sealed class RemediationAdvisor : IRemediationAdvisor
{
    private const string _promptFile = "RemediationAdvisor.txt";

    private readonly ILlmRouter _llmRouter;
    private readonly IPromptLoader _promptLoader;
    private readonly ILogger<RemediationAdvisor> _logger;

    public RemediationAdvisor(ILlmRouter llmRouter, IPromptLoader promptLoader, ILogger<RemediationAdvisor> logger)
    {
        _llmRouter = llmRouter;
        _promptLoader = promptLoader;
        _logger = logger;
    }

    public async Task<IReadOnlyList<string>> SuggestAsync(
        EnforcementResult result,
        ContractDefinition contract,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(result);
        ArgumentNullException.ThrowIfNull(contract);

        var prompt = _promptLoader.Load(_promptFile);
        var failedColumns = result.SchemaRules
            .Concat(result.QualityRules)
            .Where(rule => rule.Status is RuleStatus.Failed or RuleStatus.Warned)
            .Select(rule => rule.Column)
            .Where(column => !string.IsNullOrWhiteSpace(column))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Cast<string>()
            .ToArray();

        if (failedColumns.Length == 0)
        {
            return [];
        }

        var input = JsonSerializer.Serialize(new { contract, result, failedColumns });
        _logger.LogDebug("AI-Remediation-Prompt Prompt={Prompt}", prompt);
        var llmResult = await _llmRouter.CompleteAsync("Remediation", prompt, input, ct).ConfigureAwait(false);
        if (llmResult is null || string.IsNullOrWhiteSpace(llmResult.Content))
        {
            return BuildFallbackSuggestions(failedColumns);
        }

        try
        {
            var parsed = JsonSerializer.Deserialize<List<string>>(llmResult.Content) ?? [];
            var cleaned = parsed
                .Where(item => !string.IsNullOrWhiteSpace(item))
                .Select(item => item.Trim())
                .Take(5)
                .ToArray();
            return cleaned.Length == 0 ? BuildFallbackSuggestions(failedColumns) : cleaned;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "AI-Remediation-ParseFailed");
            return BuildFallbackSuggestions(failedColumns);
        }
    }

    private static IReadOnlyList<string> BuildFallbackSuggestions(string[] failedColumns)
    {
        return failedColumns
            .Take(5)
            .Select(column => $"Add validation and null/format checks in the upstream pipeline for column '{column}'.")
            .ToArray();
    }
}
